services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: apl-675723342.us-east-1.elb.amazonaws.com:3306
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste123
      WORDPRESS_DB_NAME: projectdb
